on: pull_request

jobs:
  validate:
    name: Validate build
    runs-on: ubuntu-latest
    container: python:3
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install build requirements for pre-requisites
      run: pip install -r build-requirements.txt
    - name: Install pre-requisites
      run: pip install --no-build-isolation -r requirements.txt
    - name: Build
      run: mkdocs build -v --clean
